# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movieinfo',
            fields=[
                ('movie_num', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_release_time', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['movie_num'],
            },
        ),
        migrations.CreateModel(
            name='Movielcritic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_num', models.IntegerField()),
                ('movie_lcritic_title', models.TextField()),
                ('movie_critic', models.TextField()),
                ('movieinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yingping.Movieinfo')),
            ],
            options={
                'ordering': ['movie_num'],
            },
        ),
        migrations.CreateModel(
            name='Moviescritic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_num', models.IntegerField()),
                ('movie_critic', models.TextField()),
                ('movieinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yingping.Movieinfo')),
            ],
            options={
                'ordering': ['movie_num'],
            },
        ),
    ]
